name: Deploy Terraform

on:
  push:
    branches:
      - main  # Déclenche l'action lors d'un push vers la branche 'main'
  pull_request:
    branches:
      - main  # Déclenche l'action pour les pull requests vers la branche 'main'

jobs:
  terraform:
    runs-on: ubuntu-latest  # Utilise l'image Ubuntu pour l'exécution du job

    steps:
      # Étape 1 : Vérifier le code source
      - name: Checkout repository
        uses: actions/checkout@v3

    # Étape 2 : Installer Terraform
      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_wrapper: false # Version de Terraform à utiliser

      # Étape 3 : Configurer AWS CLI
      - name: Set up AWS credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}  # Utilise les secrets de GitHub pour accéder à AWS
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-north-1  # Spécifiez la région AWS où vous travaillez

    

      # Étape 4 : Initialiser Terraform
      - name: Terraform Init
        run: terraform init

      # Étape 5 : Plan Terraform (affiche les actions prévues)
      - name: Terraform Plan
        run: terraform plan 

      # Étape 6 : Appliquer les changements Terraform
      - name: Terraform Apply
        run: terraform apply   # Applique les changements automatiquement
        
